---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: foo-example
  namespace: default
spec:
  serviceName: "foo-example"
  replicas: 2
  selector:
    matchLabels:
      app: foo-example
  template:
    metadata:
      labels:
        app: foo-example
    spec:
      containers:
      - name: foo
        image: localhost/foo:dev
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: TARGET
          value: "This is from stateful set"
