---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: foo-example
  name: foo-np
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: foo-example
  sessionAffinity: None
  type: NodePort
