apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: foo-example-knative
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            # NOTE: Make sure to use the name of your $PROJECT here,
            #       which is what was provided when doing a docker push
            image: gcr.io/flaviof-knative/foo
            env:
              - name: TARGET
                value: "Hello from foo on K8 deployed by knative"
